# -*- mode: sh; mode: sh-bash -*-

function ble/cmdspec/initialize { ble-import "$_ble_base/lib/@core/core-cmdspec.bash"; }
ble/is-function ble/util/idle.push && ble-import -d "$_ble_base/lib/@core/core-cmdspec.bash"


## @type cmdspec_opts
## Describes information about command line argument interpretation for each command.
## Written as optional columns separated by colons.
## Specify using a combination of the following values.
##
##    mandb-disable-man
## Do not refer to man pages when building mandb.
##
##    mandb-help
## Parse the results of $CMD --help when building mandb.
##    mandb-help=%COMMAND
## Use the COMMAND execution results when building mandb.
##    mandb-help=@HELPTEXT
## Parse HELPTEXT during mandb construction.
##    mandb-help-usage
## How to use the [-abc] [-a ARG] form when building mandb through mandb-help
## Extract options from .
##
##    mandb-usage
## Parse the results of $CMD --usage when building mandb.
##
##    mandb-exclude=REGEX
## Exclude options generated by mandb. awk correct for option name
## Specify a regular expression pattern.
##
##    plus-options
##    plus-options=xyzw
## Indicates to receive options in the format "'+' CHAR".
## If an argument is specified, it is interpreted as a set of corresponding plus options.
## For example, when xyzw is specified, it indicates that +x, +y, +z, and +w are supported.
##
##    no-options
## Indicates that the option is not interpreted.
##    stop-options-on=REX_STOP
## Do not interpret options after arguments that match the specified pattern.
##    stop-options-unless=REX_CONT
## Do not interpret options after arguments that do not match the specified pattern.
##    stop-options-at=IWORD
## Indicates that options are not interpreted in arguments after the specified position.
##    stop-options-postarg
## Normally indicates that options are not interpreted after the argument.
## This setting is overridden by stop-options-unless.
##    disable-double-hyphen
## The options after option '--' are also interpreted.
## This setting is overridden by stop-options-on.
##

builtin eval -- "${_ble_util_gdict_declare//NAME/_ble_cmdspec_opts}"

## @fn ble/cmdspec/opts [+]cmdspec_opts command...
## Sets cmdspec_opts for the specified command.
##   @param[in] opts
## When "+" is fully cured, add cmdspec_opts to the existing settings.
##   @param[in] command...
## Specifies a list of commands to add.
function ble/cmdspec/opts {
  local spec=$1 command; shift
  for command; do
    local spec1=$spec
    if [[ $spec1 == +* ]]; then
      local ret=
      ble/gdict#get _ble_cmdspec_opts "$command" "$spec1"
      spec1=${ret:+$ret:}${spec1:1}
    fi
    ble/gdict#set _ble_cmdspec_opts "$command" "$spec1"
  done
}
## @fn ble/cmdspec/opts#load command [default_value]
##   @var[out] cmdspec_opts
function ble/cmdspec/opts#load {
  cmdspec_opts=$2
  local ret=
  if ble/gdict#get _ble_cmdspec_opts "$1" ||
      { [[ $1 == */*[!/] ]] && ble/gdict#get _ble_cmdspec_opts "${1##*/}"; }
  then
    cmdspec_opts=$ret
  fi
}
